[package]
name = "ghost-army-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
ethers = { version = "2.0.14", features = ["rustls"] }
hex = "0.4.3"
tokio = { version = "1.49.0", features = ["full"] }
